import type { Metadata } from 'next';

/**
 * Single source of truth for every SEO signal the public site emits.
 *
 * Two things make this file worth having instead of hand-rolling metadata per page:
 *
 * 1. Canonicals. Next inherits `alternates` from a parent segment when a child does
 *    not set it, so a canonical declared once in the root layout would silently mark
 *    every page as a duplicate of the home page. Every route therefore declares its
 *    own, and `pageMetadata` makes that a single argument instead of a ritual.
 * 2. Open Graph. Next merges metadata shallowly — a page that sets `openGraph` at all
 *    replaces the parent's `openGraph` wholesale, dropping siteName/locale/type. The
 *    helper rebuilds the complete object every time so that cannot happen.
 *
 * The card image is generated by `app/opengraph-image.tsx`, but it is referenced here
 * explicitly rather than left to the file convention: that convention only decorates the
 * segment the file sits in, so with the root file alone every page except the home page
 * shipped with no og:image at all. Verified by grepping the rendered HTML, not assumed.
 */

export const SITE_URL = 'https://fatexia.com';
export const SITE_NAME = 'Fatexia';
export const SITE_LOCALE = 'en_US';

/** Route served by app/opengraph-image.tsx — the 1200x630 social card. */
export const OG_IMAGE = {
  url: `${SITE_URL}/opengraph-image`,
  width: 1200,
  height: 630,
  alt: 'Fatexia — the CPA network built on transparent tracking',
};

/** Contact addresses already published on the contact page — reused in Organization JSON-LD. */
export const CONTACT_EMAIL = 'hello@fatexia.com';

export function absoluteUrl(path: string): string {
  return path === '/' ? SITE_URL : `${SITE_URL}${path}`;
}

interface PageMetadataInput {
  /** Page title without the " — Fatexia" suffix; the root template appends it. */
  title: string;
  description: string;
  /** Route path, leading slash, no trailing slash (e.g. '/affiliates'). */
  path: string;
  keywords?: string[];
  /** 'article' for blog posts, otherwise the default 'website'. */
  type?: 'website' | 'article';
  publishedTime?: string;
}

export function pageMetadata({
  title,
  description,
  path,
  keywords,
  type = 'website',
  publishedTime,
}: PageMetadataInput): Metadata {
  const url = absoluteUrl(path);
  return {
    title,
    description,
    ...(keywords ? { keywords } : {}),
    alternates: { canonical: url },
    openGraph: {
      type,
      siteName: SITE_NAME,
      locale: SITE_LOCALE,
      url,
      title: `${title} — ${SITE_NAME}`,
      description,
      images: [OG_IMAGE],
      ...(publishedTime ? { publishedTime } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title: `${title} — ${SITE_NAME}`,
      description,
      images: [OG_IMAGE.url],
    },
  };
}

/* ------------------------------------------------------------------ JSON-LD -- */

/**
 * Stable @id values so the graph nodes emitted on different pages refer to the same
 * organisation and site rather than declaring a new one on every route.
 */
export const ORGANIZATION_ID = `${SITE_URL}/#organization`;
export const WEBSITE_ID = `${SITE_URL}/#website`;

export function organizationSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    '@id': ORGANIZATION_ID,
    name: SITE_NAME,
    url: SITE_URL,
    logo: {
      '@type': 'ImageObject',
      url: absoluteUrl('/logo.png'),
      width: 856,
      height: 144,
    },
    description:
      'Fatexia is a CPA affiliate network with an in-house click tracker, layered fraud detection, and payouts computed from the offer rule on every conversion.',
    email: CONTACT_EMAIL,
    contactPoint: [
      {
        '@type': 'ContactPoint',
        contactType: 'affiliate support',
        email: 'affiliates@fatexia.com',
        availableLanguage: 'English',
      },
      {
        '@type': 'ContactPoint',
        contactType: 'sales',
        email: 'advertisers@fatexia.com',
        availableLanguage: 'English',
      },
    ],
    knowsAbout: ['CPA marketing', 'Affiliate marketing', 'Click tracking', 'Ad fraud detection', 'Performance marketing'],
  };
}

export function websiteSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': WEBSITE_ID,
    url: SITE_URL,
    name: SITE_NAME,
    inLanguage: 'en',
    publisher: { '@id': ORGANIZATION_ID },
  };
}

/**
 * Breadcrumbs for a route one level below the home page. Google uses these to render
 * the site hierarchy in place of a raw URL in the result snippet.
 */
export function breadcrumbSchema(trail: { name: string; path: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [{ name: 'Home', path: '/' }, ...trail].map((crumb, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: crumb.name,
      item: absoluteUrl(crumb.path),
    })),
  };
}

export function faqSchema(faqs: { question: string; answer: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: { '@type': 'Answer', text: faq.answer },
    })),
  };
}
