const js = require('@eslint/js');
const tseslint = require('typescript-eslint');
const prettier = require('eslint-config-prettier');
const reactHooks = require('eslint-plugin-react-hooks');

/**
 * Workspace-wide config for the three apps and two packages.
 *
 * There was none before this file, so `pnpm lint` at the workspace root exited with
 * "ESLint couldn't find an eslint.config.js" and nothing in `frontend/` had ever been
 * linted — the script existed and always failed, which reads as "lint is broken" rather
 * than "lint is missing".
 *
 * Deliberately close to backend/eslint.config.js: same base rule set, same unused-vars
 * escape hatch, prettier last so formatting rules never fight the formatter. React
 * plugins are not pulled in — the type checker already covers what matters most here,
 * and a rule set nobody agreed to would land as hundreds of findings on day one.
 */
module.exports = tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/.next/**',
      '**/*.config.js',
      '**/*.config.ts',
      // Generated by Next on every build — its triple-slash reference is not ours to fix.
      '**/next-env.d.ts',
      // CommonJS shared config, not part of either app's module graph.
      'packages/config/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  prettier,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      // Browser + the handful of globals these apps actually touch. Without them every
      // `window`, `document` and `fetch` is a no-undef error.
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        crypto: 'readonly',
        FormData: 'readonly',
        URLSearchParams: 'readonly',
        AbortSignal: 'readonly',
        Response: 'readonly',
        HTMLElement: 'readonly',
        HTMLLIElement: 'readonly',
        React: 'readonly',
        process: 'readonly',
      },
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      // The codebase already carries `eslint-disable-next-line react-hooks/exhaustive-deps`
      // in several places, which errored as an unknown rule while the plugin was absent —
      // those authors were writing against a rule that was never running.
      //
      // A warning, not an error: it is the one rule here that flags real stale-closure
      // bugs, but turning it on as an error across a codebase this size would block
      // every build on findings nobody has triaged yet.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },
);
