import type { Metadata } from 'next';
import Link from 'next/link';
import { PageHero, Section } from '@/components/marketing';
import { JsonLd } from '@/components/JsonLd';
import { breadcrumbSchema, pageMetadata } from '@/lib/seo';
import { LEGAL_ADDRESS, LEGAL_EMAIL } from '@/lib/legal';

export const metadata: Metadata = pageMetadata({
  title: 'Terms of Service',
  description:
    'The terms that govern Fatexia affiliate and advertiser accounts: eligibility, tracking and attribution, prohibited traffic, payout calculation, and termination.',
  path: '/terms',
});

const SECTIONS = [
  {
    heading: '1. Acceptance of terms',
    body: `By registering for or using Fatexia's affiliate network, you agree to these Terms of Service, our Privacy Policy and Cookie Policy, and — depending on your role — the Publisher Agreement or the Advertiser Agreement, plus any offer-specific terms attached to individual campaigns. If you do not agree, do not use the network.`,
  },
  {
    heading: '2. Who operates Fatexia',
    body: `Fatexia is operated from ${LEGAL_ADDRESS}. References to "Fatexia", "we", "us" or "the network" in this document mean the operator described here.`,
  },
  {
    heading: '3. Eligibility and account approval',
    body: 'Affiliate and advertiser accounts are subject to manual review and approval before they can run live traffic or campaigns. We may decline an application, or ask for more information before approving one, at our discretion — a rejection is not required to state a reason. You must be legally able to enter into a binding agreement, and information you provide during registration must be accurate.',
  },
  {
    heading: '4. Tracking and attribution',
    body: `All clicks and conversions are tracked exclusively through Fatexia's own in-house tracker. Attempting to circumvent, spoof, or manipulate tracking — including tampering with click identifiers, forging referrer or user-agent data, or routing traffic to bypass attribution — is a material breach of these Terms and grounds for immediate account suspension and forfeiture of any unpaid balance connected to the conduct.`,
  },
  {
    heading: '5. Prohibited traffic and conduct',
    body: 'The following are prohibited on every offer unless an offer\'s own terms expressly allow them: bot or automated traffic; datacenter, hosting or known-proxy traffic presented as genuine users; cookie stuffing or forced/hidden redirects; incentivized traffic not disclosed and pre-approved for that offer; brand or trademark bidding without the advertiser\'s written permission; fake, duplicated or auto-generated leads; click injection; self-conversions or conversions generated by the affiliate\'s own actions rather than genuine third-party traffic; and any method designed to trigger a conversion event without a real, qualifying action by a real end user. Details of how we detect this traffic are in our Anti-Fraud Policy.',
  },
  {
    heading: '6. Fraud review and traffic holds',
    body: "Traffic and conversions that our fraud pipeline scores as suspicious, or that an advertiser flags, may be held pending manual review rather than paid automatically — this is separate from any hold period configured on the offer's own payout rule. A held conversion is not guaranteed to be paid; if review concludes it is invalid, it is rejected and does not count toward your balance.",
  },
  {
    heading: '7. Payouts',
    body: "Payout amounts are calculated from each offer's published payout rule at the time of conversion — never taken directly from a figure an advertiser's postback claims, only (where a rule allows it) from the sale amount the postback reports, priced at our rate. Payouts are released on the payment schedule agreed for your account once the underlying conversions have cleared fraud review and any applicable hold period.",
  },
  {
    heading: '8. Conversion reversals and chargebacks',
    body: 'An advertiser may reverse a conversion after it has been approved — for example on a returned sale, a cancelled lead, or a confirmed instance of fraud — including after it has already been paid out. A reversal on a conversion that was already paid is a chargeback: the amount is deducted from your current or future balance. If a chargeback exceeds your available balance, the deficit is carried forward and recovered from future payouts before any new balance is released.',
  },
  {
    heading: '9. Payment terms and taxes',
    body: "Payouts are made by the methods described on our Payments page, to the payment details on file for your account. You are responsible for the accuracy of those details and for any fees your payment method or provider charges on your end. You are solely responsible for determining and paying any taxes that apply to income earned through the network in your jurisdiction; Fatexia does not withhold taxes on your behalf unless legally required to.",
  },
  {
    heading: '10. Confidentiality',
    body: "Payout rates, offer terms not marked public, fraud-detection methodology, and any non-public account or performance data you receive through the network are confidential. You may not disclose them to a third party, or use them for any purpose outside operating your account, without our written consent.",
  },
  {
    heading: '11. Intellectual property',
    body: 'The Fatexia name, logo, and the software behind the tracker, dashboard and reporting are owned by Fatexia and may not be copied, reverse-engineered, or used to build a competing product. Creative assets, landing pages and offer material belong to the advertiser that supplied them and may only be used as that offer\'s terms permit.',
  },
  {
    heading: '12. Termination',
    body: "Either party may terminate an account's participation at any time, for any reason, with or without notice. We may suspend or terminate an account immediately, without notice, where we reasonably believe these Terms have been breached — in particular the prohibitions in Section 5.",
  },
  {
    heading: '13. Effect of termination',
    body: "Termination does not cancel amounts already owed. Verified, non-fraudulent conversions confirmed prior to termination remain payable on the standard payout schedule. Conversions still pending review at the time of termination are resolved under Sections 6–8 as if the account were still active. A termination for breach of Section 5 forfeits any balance directly connected to the prohibited conduct.",
  },
  {
    heading: '14. Limitation of liability',
    body: 'To the maximum extent permitted by law, Fatexia is not liable for indirect, incidental, or consequential damages arising from your use of the network, including lost profits or lost traffic opportunities. Our total liability for any claim arising from these Terms is limited to the amount actually payable to you under Section 7 for the conversions the claim concerns.',
  },
  {
    heading: '15. Indemnification',
    body: 'You agree to indemnify and hold Fatexia harmless from any claim, loss, or liability arising from your traffic, your conduct on the network, or your breach of these Terms — including claims brought by an advertiser or a third party as a result of traffic you sent.',
  },
  {
    heading: '16. Dispute resolution',
    body: "If a dispute arises, contact us first — most disagreements over a specific conversion, hold, or payout are resolved faster by your account manager reviewing the case than by any formal process. If it cannot be resolved informally within a reasonable time, either party may pursue the matter under Section 17's governing law and jurisdiction.",
  },
  {
    heading: '17. Governing law and jurisdiction',
    body: `These Terms are governed by the laws of the Czech Republic, without regard to conflict-of-law principles. Any dispute not resolved informally under Section 16 is subject to the exclusive jurisdiction of the courts of the Czech Republic.`,
  },
  {
    heading: '18. Changes to these terms',
    body: 'We may update these Terms from time to time, most often to reflect a new feature, a clarified rule, or a change in applicable law. The "Last updated" date below always reflects the current version. Continued use of the network after an update constitutes acceptance of the revised Terms.',
  },
  {
    heading: '19. Contact',
    body: `Questions about these Terms can be sent to ${LEGAL_EMAIL}, or to your account manager once your application is approved.`,
  },
];

export default function TermsPage() {
  return (
    <>
      <JsonLd data={breadcrumbSchema([{ name: 'Terms of Service', path: '/terms' }])} />
      <PageHero eyebrow="Legal" title="Terms of Service" description="The rules that govern every account on Fatexia — affiliate and advertiser alike." />
      <Section>
        <div className="mx-auto max-w-3xl">
          <p className="text-sm text-muted-foreground">Last updated: September 24, 2026</p>
          <div className="mt-10 space-y-10">
            {SECTIONS.map((s) => (
              <section key={s.heading}>
                <h2 className="text-xl font-semibold text-foreground">{s.heading}</h2>
                <p className="mt-3 leading-relaxed text-muted-foreground">{s.body}</p>
              </section>
            ))}
          </div>
          <p className="mt-12 rounded-xl border border-border bg-card p-5 text-sm text-muted-foreground">
            Affiliates should also read the{' '}
            <Link href="/publisher-agreement" className="text-primary hover:underline">
              Publisher Agreement
            </Link>{' '}
            and advertisers the{' '}
            <Link href="/advertiser-agreement" className="text-primary hover:underline">
              Advertiser Agreement
            </Link>{' '}
            for the fuller terms of their specific relationship with the network.
          </p>
        </div>
      </Section>
    </>
  );
}
