import type { Metadata } from 'next';
import Link from 'next/link';
import { PageHero, Section } from '@/components/marketing';
import { JsonLd } from '@/components/JsonLd';
import { breadcrumbSchema, pageMetadata } from '@/lib/seo';
import { LEGAL_EMAIL } from '@/lib/legal';

export const metadata: Metadata = pageMetadata({
  title: 'Anti-Fraud Policy',
  description: 'How Fatexia detects invalid traffic — the three-layer pipeline, what counts as prohibited traffic, and what happens when something is flagged.',
  path: '/anti-fraud',
});

const SECTIONS = [
  {
    heading: 'Purpose',
    body: "This policy explains, in plain language, how we tell real traffic from invalid traffic, and what happens to traffic our pipeline doesn't trust yet. It exists so every affiliate and advertiser on the network can see the mechanism rather than take a black-box score on faith — the same reasoning behind building our own tracker instead of renting one.",
  },
  {
    heading: 'Layer 1 — Datacenter and hosting filter',
    body: 'Traffic from known cloud, hosting, or datacenter ASNs is flagged before it is ever counted toward a click or a conversion. This check runs locally, at zero cost and with no external dependency, which is why it applies to every click on the network without exception.',
  },
  {
    heading: 'Layer 2 — Residential-proxy detection',
    body: "A smaller share of invalid traffic hides behind a residential IP rather than a datacenter one. For this, and only this, we use an external reputation signal — used sparingly, cached, and never treated as the sole basis for a block on its own; it feeds the same weighted score as everything else.",
  },
  {
    heading: 'Layer 3 — Click-to-conversion timing (CTIT)',
    body: "A conversion that lands implausibly fast after its click is a classic bot signature, so timing is scored alongside the other two layers. The threshold is tunable per vertical, because some legitimate offers — app installs, for example — genuinely convert fast, and a blunt fixed threshold would punish them for it.",
  },
  {
    heading: 'How the three layers combine',
    body: 'The layers feed one weighted score, not three independent gates, and the result lands in one of three bands: allow, hold-for-review, or block. We tune deliberately toward the middle band rather than an aggressive auto-block — a false positive costs an honest affiliate a real conversion, and that cost is treated as seriously as letting fraud through uncaught.',
  },
  {
    heading: 'Traffic and conduct we treat as invalid',
    body: 'Regardless of score, the following are treated as invalid or prohibited outright: bot and automated traffic; forced or hidden redirects and cookie stuffing; click injection; incentivized traffic that was not disclosed to the end user or not pre-approved for that offer; fake, duplicated, or auto-generated leads; self-conversions, including conversions generated by the affiliate\'s own actions or close associates rather than a genuine third party; and duplicate conversions from the same underlying action reported more than once.',
  },
  {
    heading: 'What happens when traffic is flagged',
    body: "Traffic in the block band never counts toward a click or conversion in the first place. Traffic in the hold band is recorded but held pending manual review rather than auto-paid — it clears into your normal balance if review confirms it's valid, or is rejected if it isn't. Clearly fraudulent traffic caught before it counts never inflates a report that later has to be reversed.",
  },
  {
    heading: 'Consequences on an account',
    body: 'A pattern of prohibited traffic under Section 5 of our Terms of Service, rather than an isolated mis-scored conversion, results in account-level consequences — a required correction of the traffic source, suspension of the affected offers, or termination of the account and forfeiture of the balance directly connected to the conduct, as described in the Terms of Service and the Publisher Agreement.',
  },
  {
    heading: 'If you think something was mis-scored',
    body: 'Score-based systems are not perfect, and we would rather you tell us about a false positive than quietly lose trust in the network. If you believe a hold or rejection was wrong, contact your account manager with the conversion or click reference — they can look into exactly why the pipeline scored it the way it did.',
  },
  {
    heading: 'Reporting suspected fraud',
    body: (
      <>
        Advertisers who spot a traffic source we haven&apos;t caught should report it — see the Advertiser Agreement, or write to{' '}
        <Link href="/contact" className="text-primary hover:underline">
          our contact page
        </Link>
        . We investigate and, where warranted, hold or reject the affiliated conversions and act on the account responsible.
      </>
    ),
  },
  {
    heading: 'Changes to this policy',
    body: 'We refine the pipeline as new patterns show up, so the specifics of what is scored may change even where the layers described above stay the same. Material changes will be reflected here with an updated date.',
  },
  {
    heading: 'Contact',
    body: `Questions about this policy can be sent to ${LEGAL_EMAIL}.`,
  },
];

export default function AntiFraudPage() {
  return (
    <>
      <JsonLd data={breadcrumbSchema([{ name: 'Anti-Fraud Policy', path: '/anti-fraud' }])} />
      <PageHero eyebrow="Legal" title="Anti-Fraud Policy" description="How the three-layer pipeline works, what counts as invalid traffic, and what happens when something is flagged." />
      <Section>
        <div className="mx-auto max-w-3xl">
          <p className="text-sm text-muted-foreground">Last updated: September 24, 2026</p>
          <div className="mt-10 space-y-10 text-sm leading-relaxed text-muted-foreground">
            {SECTIONS.map((s) => (
              <section key={s.heading}>
                <h2 className="text-xl font-semibold text-foreground">{s.heading}</h2>
                <p className="mt-3">{s.body}</p>
              </section>
            ))}
          </div>
        </div>
      </Section>
    </>
  );
}
