import { Column, CreateDateColumn, Entity, Index, PrimaryColumn } from 'typeorm';

export enum ClickQualityStatus {
  GOOD = 'GOOD',
  SUSPECT = 'SUSPECT',
  BLOCKED = 'BLOCKED',
  // The fraud pipeline's fail-open state — quota-exhausted or unavailable signals
  // mean this click was never fully scored, not that it's clean (see PLAN-tracker.md).
  UNSCORED = 'UNSCORED',
}

@Entity('clicks')
export class Click {
  // The PK doubles as the {click_id} embedded in the offer's destination URL —
  // one identifier, generated by the Tracker before the redirect fires.
  @PrimaryColumn('uuid')
  id!: string;

  @Index()
  @Column({ type: 'uuid' })
  offerId!: string;

  // Nullable: a click can arrive with a missing/invalid affiliateId (bad link,
  // tampering). Still logged — a null attribution is itself a fraud signal — but
  // never attributed to a real affiliate for payout.
  @Index()
  @Column({ type: 'uuid', nullable: true })
  affiliateId!: string | null;

  @Column({ type: 'varchar' })
  ip!: string;

  @Column({ type: 'varchar', nullable: true })
  userAgent!: string | null;

  @Index()
  @Column({ type: 'varchar', nullable: true })
  countryCode!: string | null;

  // City-level geo, read from the same GeoLite2-City lookup that resolves the country.
  @Column({ type: 'varchar', nullable: true })
  city!: string | null;

  @Column({ type: 'varchar', nullable: true })
  region!: string | null;

  @Column({ type: 'varchar', nullable: true })
  regionCode!: string | null;

  @Column({ type: 'varchar', nullable: true })
  deviceType!: string | null;

  @Column({ type: 'varchar', nullable: true })
  deviceBrand!: string | null;

  @Column({ type: 'varchar', nullable: true })
  os!: string | null;

  @Column({ type: 'varchar', nullable: true })
  osVersion!: string | null;

  @Column({ type: 'varchar', nullable: true })
  browser!: string | null;

  @Column({ type: 'varchar', nullable: true })
  browserVersion!: string | null;

  @Column({ type: 'varchar', nullable: true })
  asn!: string | null;

  @Column({ type: 'boolean', default: false })
  isDatacenter!: boolean;

  // null = the proxy/VPN check never ran (no local signal, all API providers
  // skipped/exhausted) — distinct from a confirmed false.
  @Column({ type: 'boolean', nullable: true })
  isProxyOrVpn!: boolean | null;

  // Affiliate-supplied pass-through parameters carried on the tracking link. Kept on
  // the click (not just the conversion) so the Sub-ID report can show click volume
  // per sub-id, not only converted traffic.
  @Column({ type: 'varchar', nullable: true })
  subId1!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId2!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId3!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId4!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId5!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId6!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId7!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId8!: string | null;

  @Column({ type: 'varchar', nullable: true })
  referer!: string | null;

  // First click for this offer+IP inside the 24h window (see unique-click.ts).
  // Decided at write time so the per-row badge and the aggregate `uniqueClicks`
  // metric in reports share one definition rather than two that can disagree.
  @Column({ type: 'boolean', default: false })
  isUnique!: boolean;

  @Column({ type: 'smallint', default: 0 })
  riskScore!: number;

  @Column({ type: 'enum', enum: ClickQualityStatus, default: ClickQualityStatus.UNSCORED })
  qualityStatus!: ClickQualityStatus;

  @Index()
  @CreateDateColumn({ type: 'timestamp' })
  createdAt!: Date;
}
