import { Column, CreateDateColumn, Entity, Index, PrimaryColumn } from 'typeorm';
import { refIdTransformer } from '../../common/ref-id';

export enum ClickQualityStatus {
  GOOD = 'GOOD',
  SUSPECT = 'SUSPECT',
  BLOCKED = 'BLOCKED',
  // The fraud pipeline's fail-open state — quota-exhausted or unavailable signals
  // mean this click was never fully scored, not that it's clean (see PLAN-tracker.md).
  UNSCORED = 'UNSCORED',
}

@Entity('clicks')
export class Click {
  // Internal key, generated by the Tracker before the redirect fires. It used to double
  // as the {click_id} in the destination URL; that is now `refId`, which an advertiser
  // can actually read back to us. Postbacks still accept either (see postback.service).
  @PrimaryColumn('uuid')
  id!: string;

  /**
   * The short number an advertiser sees as `click_id` and posts back.
   *
   * Unlike the other refId columns this one is written by the Tracker, not defaulted by
   * the database: the id goes into the redirect URL before the row is written, so it
   * cannot wait on a round trip. click-ref-id.ts draws blocks from the sequence ahead of
   * time. The column keeps a DEFAULT anyway, so any other insert path (the seed, a
   * fixture) still produces a valid row.
   */
  @Index('UQ_clicks_refId', { unique: true })
  @Column({ type: 'bigint', transformer: refIdTransformer })
  refId!: number;

  @Index()
  @Column({ type: 'uuid' })
  offerId!: string;

  // Nullable: a click can arrive with a missing/invalid affiliateId (bad link,
  // tampering). Still logged — a null attribution is itself a fraud signal — but
  // never attributed to a real affiliate for payout.
  @Index()
  @Column({ type: 'uuid', nullable: true })
  affiliateId!: string | null;

  /**
   * The smart-link this click came through, or null for a direct offer click.
   *
   * Recorded because the smart-link's revenue share has to be applied when the
   * conversion arrives, which can be days later — by then the only way back to the
   * link is this column. The rotation already resolved to a single offer, so without
   * it a smart-link click is indistinguishable from a direct one.
   */
  @Index()
  @Column({ type: 'uuid', nullable: true })
  smartLinkId!: string | null;

  @Column({ type: 'varchar' })
  ip!: string;

  @Column({ type: 'varchar', nullable: true })
  userAgent!: string | null;

  @Index()
  @Column({ type: 'varchar', nullable: true })
  countryCode!: string | null;

  // City-level geo, read from the same GeoLite2-City lookup that resolves the country.
  @Column({ type: 'varchar', nullable: true })
  city!: string | null;

  @Column({ type: 'varchar', nullable: true })
  region!: string | null;

  @Column({ type: 'varchar', nullable: true })
  regionCode!: string | null;

  @Column({ type: 'varchar', nullable: true })
  deviceType!: string | null;

  @Column({ type: 'varchar', nullable: true })
  deviceBrand!: string | null;

  @Column({ type: 'varchar', nullable: true })
  os!: string | null;

  @Column({ type: 'varchar', nullable: true })
  osVersion!: string | null;

  @Column({ type: 'varchar', nullable: true })
  browser!: string | null;

  @Column({ type: 'varchar', nullable: true })
  browserVersion!: string | null;

  @Column({ type: 'varchar', nullable: true })
  asn!: string | null;

  @Column({ type: 'boolean', default: false })
  isDatacenter!: boolean;

  // null = the proxy/VPN check never ran (no local signal, all API providers
  // skipped/exhausted) — distinct from a confirmed false.
  @Column({ type: 'boolean', nullable: true })
  isProxyOrVpn!: boolean | null;

  // Affiliate-supplied pass-through parameters carried on the tracking link. Kept on
  // the click (not just the conversion) so the Sub-ID report can show click volume
  // per sub-id, not only converted traffic.
  @Column({ type: 'varchar', nullable: true })
  subId1!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId2!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId3!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId4!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId5!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId6!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId7!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId8!: string | null;

  @Column({ type: 'varchar', nullable: true })
  referer!: string | null;

  // First click for this offer+IP inside the 24h window (see unique-click.ts).
  // Decided at write time so the per-row badge and the aggregate `uniqueClicks`
  // metric in reports share one definition rather than two that can disagree.
  @Column({ type: 'boolean', default: false })
  isUnique!: boolean;

  @Column({ type: 'smallint', default: 0 })
  riskScore!: number;

  @Column({ type: 'enum', enum: ClickQualityStatus, default: ClickQualityStatus.UNSCORED })
  qualityStatus!: ClickQualityStatus;

  @Index()
  @CreateDateColumn({ type: 'timestamp' })
  createdAt!: Date;
}
