import { Column, CreateDateColumn, Entity, Index, PrimaryColumn } from 'typeorm';
import { refIdTransformer } from '../../common/ref-id';

export enum ClickQualityStatus {
  GOOD = 'GOOD',
  SUSPECT = 'SUSPECT',
  BLOCKED = 'BLOCKED',
  // The fraud pipeline's fail-open state — quota-exhausted or unavailable signals
  // mean this click was never fully scored, not that it's clean (see PLAN-tracker.md).
  UNSCORED = 'UNSCORED',
}

@Entity('clicks')
export class Click {
  // Internal key, generated by the Tracker before the redirect fires. It used to double
  // as the {click_id} in the destination URL; that is now `refId`, which an advertiser
  // can actually read back to us. Postbacks still accept either (see postback.service).
  @PrimaryColumn('uuid')
  id!: string;

  /**
   * The short number an advertiser sees as `click_id` and posts back.
   *
   * Unlike the other refId columns this one is written by the Tracker, not defaulted by
   * the database: the id goes into the redirect URL before the row is written, so it
   * cannot wait on a round trip. click-ref-id.ts draws blocks from the sequence ahead of
   * time. The column keeps a DEFAULT anyway, so any other insert path (the seed, a
   * fixture) still produces a valid row.
   */
  @Index('UQ_clicks_refId', { unique: true })
  @Column({ type: 'bigint', transformer: refIdTransformer })
  refId!: number;

  @Index()
  @Column({ type: 'uuid' })
  offerId!: string;

  // Nullable: a click can arrive with a missing/invalid affiliateId (bad link,
  // tampering). Still logged — a null attribution is itself a fraud signal — but
  // never attributed to a real affiliate for payout.
  @Index()
  @Column({ type: 'uuid', nullable: true })
  affiliateId!: string | null;

  /**
   * The smart-link this click came through, or null for a direct offer click.
   *
   * Recorded because the smart-link's revenue share has to be applied when the
   * conversion arrives, which can be days later — by then the only way back to the
   * link is this column. The rotation already resolved to a single offer, so without
   * it a smart-link click is indistinguishable from a direct one.
   */
  @Index()
  @Column({ type: 'uuid', nullable: true })
  smartLinkId!: string | null;

  @Column({ type: 'varchar' })
  ip!: string;

  @Column({ type: 'varchar', nullable: true })
  userAgent!: string | null;

  @Index()
  @Column({ type: 'varchar', nullable: true })
  countryCode!: string | null;

  @Column({ type: 'varchar', nullable: true })
  countryName!: string | null;

  /**
   * Where the address block is registered, as opposed to where it answered from.
   *
   * A mismatch against `countryCode` is normal for a VPN and unusual for organic
   * traffic, which makes it fraud reasoning — network-side only, like `asn` and the
   * proxy flags.
   */
  @Column({ type: 'varchar', nullable: true })
  registeredCountryCode!: string | null;

  @Column({ type: 'varchar', nullable: true })
  continentCode!: string | null;

  @Column({ type: 'varchar', nullable: true })
  continentName!: string | null;

  // City-level geo, read from the same GeoLite2-City lookup that resolves the country.
  @Column({ type: 'varchar', nullable: true })
  city!: string | null;

  /** GeoNames id for the city — the stable handle behind a name that has spelling variants. */
  @Column({ type: 'integer', nullable: true })
  cityGeonameId!: number | null;

  @Column({ type: 'varchar', nullable: true })
  region!: string | null;

  @Column({ type: 'varchar', nullable: true })
  regionCode!: string | null;

  // Second-level subdivision (a county, a district) where MaxMind has one.
  @Column({ type: 'varchar', nullable: true })
  region2!: string | null;

  @Column({ type: 'varchar', nullable: true })
  region2Code!: string | null;

  @Column({ type: 'varchar', nullable: true })
  postalCode!: string | null;

  // decimal, not float — and read back as a string, like every other decimal column
  // here. Four places is about 11 metres, well inside MaxMind's best accuracy radius.
  @Column({ type: 'decimal', precision: 8, scale: 4, nullable: true })
  latitude!: string | null;

  @Column({ type: 'decimal', precision: 8, scale: 4, nullable: true })
  longitude!: string | null;

  /**
   * MaxMind's own confidence in the coordinates, in kilometres.
   *
   * Stored with them deliberately. 8.8.8.8 resolves to a point in Kansas with a 1000km
   * radius — that is "somewhere in the United States", and without this column the
   * coordinates read as a location.
   */
  @Column({ type: 'smallint', nullable: true })
  accuracyRadiusKm!: number | null;

  /** IANA zone, e.g. `America/New_York`. */
  @Column({ type: 'varchar', nullable: true })
  timeZone!: string | null;

  /** US metro/DMA code; null everywhere else. */
  @Column({ type: 'smallint', nullable: true })
  metroCode!: number | null;

  @Column({ type: 'varchar', nullable: true })
  deviceType!: string | null;

  @Column({ type: 'varchar', nullable: true })
  deviceBrand!: string | null;

  @Column({ type: 'varchar', nullable: true })
  os!: string | null;

  @Column({ type: 'varchar', nullable: true })
  osVersion!: string | null;

  @Column({ type: 'varchar', nullable: true })
  browser!: string | null;

  @Column({ type: 'varchar', nullable: true })
  browserVersion!: string | null;

  @Column({ type: 'varchar', nullable: true })
  asn!: string | null;

  // The same ASN split apart. `asn` is the combined string the datacenter keyword filter
  // reads; these two are what a report can actually group or filter on, since "7922
  // Comcast Cable Communications, LLC" is not a number and not an organisation.
  @Column({ type: 'integer', nullable: true })
  asnNumber!: number | null;

  @Column({ type: 'varchar', nullable: true })
  asnOrganization!: string | null;

  // MaxMind's own legacy traits. Distinct from `isProxyOrVpn`, which is the residential
  // -proxy cascade's verdict — these come free with the city record and are null when
  // GeoLite2 does not set them, which is most of the time.
  @Column({ type: 'boolean', nullable: true })
  isAnonymousProxy!: boolean | null;

  @Column({ type: 'boolean', nullable: true })
  isSatelliteProvider!: boolean | null;

  @Column({ type: 'boolean', default: false })
  isDatacenter!: boolean;

  // null = the proxy/VPN check never ran (no local signal, all API providers
  // skipped/exhausted) — distinct from a confirmed false.
  @Column({ type: 'boolean', nullable: true })
  isProxyOrVpn!: boolean | null;

  // Affiliate-supplied pass-through parameters carried on the tracking link. Kept on
  // the click (not just the conversion) so the Sub-ID report can show click volume
  // per sub-id, not only converted traffic.
  @Column({ type: 'varchar', nullable: true })
  subId1!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId2!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId3!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId4!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId5!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId6!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId7!: string | null;

  @Column({ type: 'varchar', nullable: true })
  subId8!: string | null;

  @Column({ type: 'varchar', nullable: true })
  referer!: string | null;

  // First click for this offer+IP inside the 24h window (see unique-click.ts).
  // Decided at write time so the per-row badge and the aggregate `uniqueClicks`
  // metric in reports share one definition rather than two that can disagree.
  @Column({ type: 'boolean', default: false })
  isUnique!: boolean;

  @Column({ type: 'smallint', default: 0 })
  riskScore!: number;

  @Column({ type: 'enum', enum: ClickQualityStatus, default: ClickQualityStatus.UNSCORED })
  qualityStatus!: ClickQualityStatus;

  @Index()
  @CreateDateColumn({ type: 'timestamp' })
  createdAt!: Date;
}
