import { MigrationInterface, QueryRunner } from "typeorm";

export class AdminSurfaceModules1785400000000 implements MigrationInterface {
    name = 'AdminSurfaceModules1785400000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "affiliate_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "affiliateIds" jsonb NOT NULL DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_dde86f5254722ee71a9ce93d079" UNIQUE ("name"), CONSTRAINT "PK_c8a75d39f613af8486b7e6dfb3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "affiliate_points" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "affiliateId" uuid NOT NULL, "conversionId" uuid, "points" integer NOT NULL, "reason" character varying NOT NULL, "createdByUserId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ec38884d357b13be0c8ffb772eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e20d4e4908cd01e6c4860af596" ON "affiliate_points" ("affiliateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_21bdb51f130e67df50e99eb58d" ON "affiliate_points" ("createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."offer_access_requests_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "offer_access_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "offerId" uuid NOT NULL, "affiliateId" uuid NOT NULL, "status" "public"."offer_access_requests_status_enum" NOT NULL DEFAULT 'PENDING', "affiliateNote" text, "decisionNote" text, "decidedByUserId" uuid, "decidedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6eb1fcf83c2b1eccb3e70eb2d80" UNIQUE ("offerId", "affiliateId"), CONSTRAINT "PK_bdf28f14af315a260594b54ea37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac3e3e13cdbee81f3b6795a7b4" ON "offer_access_requests" ("offerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_08b5a53e4725627995e71891de" ON "offer_access_requests" ("affiliateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f6ce60486433c51f5027ed7af9" ON "offer_access_requests" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."smart_links_rotation_enum" AS ENUM('TOP_PAYOUT', 'ROUND_ROBIN', 'BEST_CR')`);
        await queryRunner.query(`CREATE TYPE "public"."smart_links_status_enum" AS ENUM('ACTIVE', 'PAUSED')`);
        await queryRunner.query(`CREATE TABLE "smart_links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "offerIds" jsonb NOT NULL DEFAULT '[]', "countries" jsonb NOT NULL DEFAULT '[]', "devices" jsonb NOT NULL DEFAULT '[]', "rotation" "public"."smart_links_rotation_enum" NOT NULL DEFAULT 'TOP_PAYOUT', "status" "public"."smart_links_status_enum" NOT NULL DEFAULT 'ACTIVE', "fallbackUrl" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9920adc9befdeed3785abc66940" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3a901aac8b521e5cf506a8f2f3" ON "smart_links" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."conversions_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'DUPLICATE', 'PAID', 'CHARGEBACK')`);
        await queryRunner.query(`CREATE TABLE "conversions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clickId" uuid, "offerId" uuid NOT NULL, "affiliateId" uuid, "revenueAmount" numeric(12,2) NOT NULL DEFAULT '0', "payoutAmount" numeric(12,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'USD', "status" "public"."conversions_status_enum" NOT NULL DEFAULT 'PENDING', "isDuplicate" boolean NOT NULL DEFAULT false, "isOrphan" boolean NOT NULL DEFAULT false, "leadRiskScore" integer NOT NULL DEFAULT '0', "emailHash" character varying, "phoneHash" character varying, "ctitMs" integer, "subId1" character varying, "subId2" character varying, "subId3" character varying, "countryCode" character varying(2), "transactionId" character varying, "approvedAt" TIMESTAMP, "paidAt" TIMESTAMP, "invoiceId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4af8c6388f42a1849ee9b22fa16" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_579e4623c191978b45dea673bd" ON "conversions" ("clickId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d781c3fabe1d0af445114e5712" ON "conversions" ("offerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c559ae52acd7eb26d78d0b5949" ON "conversions" ("affiliateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_147f1baf41b5c6a49acc2897a3" ON "conversions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_38011c83f462143718985dd602" ON "conversions" ("invoiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a5699e9bc3f31efa1d6579ae1" ON "conversions" ("createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."postback_logs_direction_enum" AS ENUM('INBOUND', 'OUTBOUND')`);
        await queryRunner.query(`CREATE TABLE "postback_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversionId" uuid, "offerId" uuid, "affiliateId" uuid, "direction" "public"."postback_logs_direction_enum" NOT NULL, "url" character varying, "payload" jsonb NOT NULL DEFAULT '{}', "responseStatus" integer, "success" boolean NOT NULL DEFAULT false, "errorMessage" text, "attemptCount" integer NOT NULL DEFAULT '1', "sourceIp" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bffdb5433f559ab4765ec66e10a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_16f6d07a3a6c662bb8d00b59d8" ON "postback_logs" ("conversionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_815cd14f0b943d678c182affb7" ON "postback_logs" ("offerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_228a69964277a29e6cdd973b5e" ON "postback_logs" ("affiliateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccd34d8c4aaaef14372c7ff247" ON "postback_logs" ("direction") `);
        await queryRunner.query(`CREATE INDEX "IDX_5900ea9e4de29e359bf945c1b1" ON "postback_logs" ("createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('DRAFT', 'PENDING', 'APPROVED', 'PAID', 'REJECTED')`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_paymentmethod_enum" AS ENUM('BANK_TRANSFER', 'PAYPAL')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceNumber" character varying NOT NULL, "affiliateId" uuid NOT NULL, "periodFrom" TIMESTAMP NOT NULL, "periodTo" TIMESTAMP NOT NULL, "amount" numeric(12,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'USD', "conversionCount" integer NOT NULL DEFAULT '0', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'DRAFT', "paymentMethod" "public"."invoices_paymentmethod_enum" NOT NULL DEFAULT 'BANK_TRANSFER', "paymentReference" character varying, "notes" text, "paidAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bf8e0f9dd4558ef209ec111782" ON "invoices" ("invoiceNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d491577e584314d16a5285e7c" ON "invoices" ("affiliateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac0f09364e3701d9ed35435288" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_plan_enum" AS ENUM('STARTER', 'GROWTH', 'ENTERPRISE')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_billingcycle_enum" AS ENUM('MONTHLY', 'QUARTERLY', 'ANNUAL')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "advertiserId" uuid NOT NULL, "plan" "public"."subscriptions_plan_enum" NOT NULL DEFAULT 'STARTER', "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'TRIAL', "billingCycle" "public"."subscriptions_billingcycle_enum" NOT NULL DEFAULT 'MONTHLY', "amount" numeric(12,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'USD', "startedAt" TIMESTAMP NOT NULL, "renewsAt" TIMESTAMP, "cancelledAt" TIMESTAMP, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f0d26661abf5fd7bb211a087bc" ON "subscriptions" ("advertiserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf973355b70645eff37774de" ON "subscriptions" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."messages_direction_enum" AS ENUM('OUTBOUND', 'INBOUND')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "affiliateId" uuid NOT NULL, "direction" "public"."messages_direction_enum" NOT NULL, "subject" character varying NOT NULL, "body" text NOT NULL, "senderUserId" uuid, "readAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_98ae63075bee3b82c5158b6d2c" ON "messages" ("affiliateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ce6acdb0801254590f8a78c08" ON "messages" ("createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_level_enum" AS ENUM('INFO', 'SUCCESS', 'WARNING', 'ERROR')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_category_enum" AS ENUM('OFFER', 'AFFILIATE', 'CONVERSION', 'FRAUD', 'BILLING', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "level" "public"."notifications_level_enum" NOT NULL DEFAULT 'INFO', "category" "public"."notifications_category_enum" NOT NULL DEFAULT 'SYSTEM', "title" character varying NOT NULL, "body" text NOT NULL, "link" character varying, "readAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_831a5a06f879fb0bebf8965871" ON "notifications" ("createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."news_posts_status_enum" AS ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TYPE "public"."news_posts_audience_enum" AS ENUM('ALL', 'AFFILIATES', 'ADVERTISERS')`);
        await queryRunner.query(`CREATE TABLE "news_posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "slug" character varying NOT NULL, "excerpt" character varying, "body" text NOT NULL, "status" "public"."news_posts_status_enum" NOT NULL DEFAULT 'DRAFT', "audience" "public"."news_posts_audience_enum" NOT NULL DEFAULT 'ALL', "pinned" boolean NOT NULL DEFAULT false, "authorUserId" uuid, "publishedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_95a44578e2b4bb7ca42e3ef4de6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f95fffe8fe305779d91176ffce" ON "news_posts" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."email_templates_templatekey_enum" AS ENUM('AFFILIATE_WELCOME', 'PASSWORD_RESET', 'ACCESS_REQUEST_APPROVED', 'ACCESS_REQUEST_REJECTED', 'AFFILIATE_APPROVED', 'AFFILIATE_SUSPENDED', 'PAYOUT_SENT', 'OFFER_LIVE')`);
        await queryRunner.query(`CREATE TABLE "email_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "templateKey" "public"."email_templates_templatekey_enum" NOT NULL, "name" character varying NOT NULL, "subject" character varying NOT NULL, "body" text NOT NULL, "availableMacros" jsonb NOT NULL DEFAULT '[]', "enabled" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_91adcdfea7b276e2e4787981a41" UNIQUE ("templateKey"), CONSTRAINT "PK_06c564c515d8cdb40b6f3bfbbb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "network_settings" ("id" character varying NOT NULL, "networkName" character varying NOT NULL DEFAULT 'Fatexia', "supportEmail" character varying, "defaultCurrency" character varying NOT NULL DEFAULT 'USD', "timezone" character varying NOT NULL DEFAULT 'UTC', "defaultHoldDays" integer NOT NULL DEFAULT '30', "minimumPayoutThreshold" numeric(12,2) NOT NULL DEFAULT '50', "payoutCycleDays" integer NOT NULL DEFAULT '30', "autoApproveAffiliates" boolean NOT NULL DEFAULT false, "autoApproveConversions" boolean NOT NULL DEFAULT false, "pointsPerConversion" integer NOT NULL DEFAULT '10', "fraudSuspectThreshold" integer NOT NULL DEFAULT '30', "fraudBlockThreshold" integer NOT NULL DEFAULT '70', "loginRateLimitPerMinute" integer NOT NULL DEFAULT '10', "clickRateLimitPerMinute" integer NOT NULL DEFAULT '600', "smtpHost" character varying, "smtpPort" integer, "smtpUser" character varying, "smtpFromEmail" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_df1d564d39cb52f7b62d908b083" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."integrations_provider_enum" AS ENUM('IPHUB', 'IPAPI_IS', 'IPQS', 'MAXMIND', 'SMTP', 'PAYPAL', 'WISE')`);
        await queryRunner.query(`CREATE TYPE "public"."integrations_status_enum" AS ENUM('NOT_CONFIGURED', 'ACTIVE', 'DISABLED', 'ERROR')`);
        await queryRunner.query(`CREATE TABLE "integrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider" "public"."integrations_provider_enum" NOT NULL, "name" character varying NOT NULL, "description" text, "apiKey" character varying, "apiSecret" character varying, "config" jsonb NOT NULL DEFAULT '{}', "status" "public"."integrations_status_enum" NOT NULL DEFAULT 'NOT_CONFIGURED', "lastCheckedAt" TIMESTAMP, "lastError" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5297e5d1d49d1831c86a609fe3f" UNIQUE ("provider"), CONSTRAINT "PK_9adcdc6d6f3922535361ce641e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "affiliates" ADD "postbackUrl" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "affiliates" ADD "referredByAffiliateId" uuid`);
        await queryRunner.query(`ALTER TABLE "affiliates" ADD "referralCode" character varying(40)`);
        await queryRunner.query(`ALTER TABLE "affiliates" ADD "assignedManagerId" uuid`);
        await queryRunner.query(`CREATE TYPE "public"."affiliates_payoutmethod_enum" AS ENUM('BANK_TRANSFER', 'PAYPAL')`);
        await queryRunner.query(`ALTER TABLE "affiliates" ADD "payoutMethod" "public"."affiliates_payoutmethod_enum"`);
        await queryRunner.query(`ALTER TABLE "affiliates" ADD "payoutDetails" jsonb NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "managers" ADD "fullName" character varying(120)`);
        await queryRunner.query(`ALTER TABLE "managers" ADD "phone" character varying(40)`);
        await queryRunner.query(`ALTER TABLE "managers" ADD "skype" character varying(120)`);
        await queryRunner.query(`ALTER TABLE "managers" ADD "defaultCommissionPercent" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "managers" ADD "notes" text`);
        await queryRunner.query(`CREATE TYPE "public"."advertisers_status_enum" AS ENUM('PENDING', 'ACTIVE', 'SUSPENDED')`);
        await queryRunner.query(`ALTER TABLE "advertisers" ADD "status" "public"."advertisers_status_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "advertisers" ADD "contactName" character varying`);
        await queryRunner.query(`ALTER TABLE "advertisers" ADD "contactEmail" character varying`);
        await queryRunner.query(`ALTER TABLE "advertisers" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "advertisers" ADD "country" character varying`);
        await queryRunner.query(`ALTER TABLE "advertisers" ADD "websiteUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "advertisers" ADD "accountManagerId" uuid`);
        await queryRunner.query(`ALTER TABLE "advertisers" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "advertisers" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clicks" ADD "subId1" character varying`);
        await queryRunner.query(`ALTER TABLE "clicks" ADD "subId2" character varying`);
        await queryRunner.query(`ALTER TABLE "clicks" ADD "subId3" character varying`);
        await queryRunner.query(`ALTER TABLE "clicks" ADD "referer" character varying`);
        await queryRunner.query(`ALTER TABLE "payout_rules" ALTER COLUMN "revenueAmount" SET DEFAULT '0.00'`);
        await queryRunner.query(`CREATE INDEX "IDX_cd4d6f239b9fbca48b3b7f6739" ON "affiliates" ("referredByAffiliateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_63e324f59994deb005a8bea2cb" ON "affiliates" ("assignedManagerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f446c32656bff460fbe89b3d35" ON "advertisers" ("status") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_f446c32656bff460fbe89b3d35"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63e324f59994deb005a8bea2cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd4d6f239b9fbca48b3b7f6739"`);
        await queryRunner.query(`ALTER TABLE "payout_rules" ALTER COLUMN "revenueAmount" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "clicks" DROP COLUMN "referer"`);
        await queryRunner.query(`ALTER TABLE "clicks" DROP COLUMN "subId3"`);
        await queryRunner.query(`ALTER TABLE "clicks" DROP COLUMN "subId2"`);
        await queryRunner.query(`ALTER TABLE "clicks" DROP COLUMN "subId1"`);
        await queryRunner.query(`ALTER TABLE "advertisers" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "advertisers" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "advertisers" DROP COLUMN "accountManagerId"`);
        await queryRunner.query(`ALTER TABLE "advertisers" DROP COLUMN "websiteUrl"`);
        await queryRunner.query(`ALTER TABLE "advertisers" DROP COLUMN "country"`);
        await queryRunner.query(`ALTER TABLE "advertisers" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "advertisers" DROP COLUMN "contactEmail"`);
        await queryRunner.query(`ALTER TABLE "advertisers" DROP COLUMN "contactName"`);
        await queryRunner.query(`ALTER TABLE "advertisers" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."advertisers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "managers" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "managers" DROP COLUMN "defaultCommissionPercent"`);
        await queryRunner.query(`ALTER TABLE "managers" DROP COLUMN "skype"`);
        await queryRunner.query(`ALTER TABLE "managers" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "managers" DROP COLUMN "fullName"`);
        await queryRunner.query(`ALTER TABLE "affiliates" DROP COLUMN "payoutDetails"`);
        await queryRunner.query(`ALTER TABLE "affiliates" DROP COLUMN "payoutMethod"`);
        await queryRunner.query(`DROP TYPE "public"."affiliates_payoutmethod_enum"`);
        await queryRunner.query(`ALTER TABLE "affiliates" DROP COLUMN "assignedManagerId"`);
        await queryRunner.query(`ALTER TABLE "affiliates" DROP COLUMN "referralCode"`);
        await queryRunner.query(`ALTER TABLE "affiliates" DROP COLUMN "referredByAffiliateId"`);
        await queryRunner.query(`ALTER TABLE "affiliates" DROP COLUMN "postbackUrl"`);
        await queryRunner.query(`DROP TABLE "integrations"`);
        await queryRunner.query(`DROP TYPE "public"."integrations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."integrations_provider_enum"`);
        await queryRunner.query(`DROP TABLE "network_settings"`);
        await queryRunner.query(`DROP TABLE "email_templates"`);
        await queryRunner.query(`DROP TYPE "public"."email_templates_templatekey_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f95fffe8fe305779d91176ffce"`);
        await queryRunner.query(`DROP TABLE "news_posts"`);
        await queryRunner.query(`DROP TYPE "public"."news_posts_audience_enum"`);
        await queryRunner.query(`DROP TYPE "public"."news_posts_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_831a5a06f879fb0bebf8965871"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ce6acdb0801254590f8a78c08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98ae63075bee3b82c5158b6d2c"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."messages_direction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf973355b70645eff37774de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0d26661abf5fd7bb211a087bc"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_billingcycle_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_plan_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac0f09364e3701d9ed35435288"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d491577e584314d16a5285e7c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf8e0f9dd4558ef209ec111782"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5900ea9e4de29e359bf945c1b1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccd34d8c4aaaef14372c7ff247"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_228a69964277a29e6cdd973b5e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_815cd14f0b943d678c182affb7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16f6d07a3a6c662bb8d00b59d8"`);
        await queryRunner.query(`DROP TABLE "postback_logs"`);
        await queryRunner.query(`DROP TYPE "public"."postback_logs_direction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a5699e9bc3f31efa1d6579ae1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38011c83f462143718985dd602"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_147f1baf41b5c6a49acc2897a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c559ae52acd7eb26d78d0b5949"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d781c3fabe1d0af445114e5712"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_579e4623c191978b45dea673bd"`);
        await queryRunner.query(`DROP TABLE "conversions"`);
        await queryRunner.query(`DROP TYPE "public"."conversions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a901aac8b521e5cf506a8f2f3"`);
        await queryRunner.query(`DROP TABLE "smart_links"`);
        await queryRunner.query(`DROP TYPE "public"."smart_links_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."smart_links_rotation_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6ce60486433c51f5027ed7af9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08b5a53e4725627995e71891de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac3e3e13cdbee81f3b6795a7b4"`);
        await queryRunner.query(`DROP TABLE "offer_access_requests"`);
        await queryRunner.query(`DROP TYPE "public"."offer_access_requests_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21bdb51f130e67df50e99eb58d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e20d4e4908cd01e6c4860af596"`);
        await queryRunner.query(`DROP TABLE "affiliate_points"`);
        await queryRunner.query(`DROP TABLE "affiliate_groups"`);
    }

}
